
* Dopamine
** Andrew Huberman : Controlling Your Dopamine For Motivation, Focus & Satisfaction | Huberman Lab Podcast #39

https://www.youtube.com/watch?v=QmOF0crdyRU&ab_channel=AndrewHuberman

cold water increases happens after 10-15min to 225% and it sustained
noraperelin
apeneprin (adrenaline)
dopamin
cortisol

how to decrease cortisol

*** What is dopamine

baseline dopamine level

peaks Tonic (low level) and phasic (peaks) release
after peak, baseline level dips

motivation, desire, excited, pursuit


neurotransmitter : local communication between neurons

neuromodulator : macro level communication between neurons

how it works?
controls motivation, drive, craving, time perception

important for movement

parkinson - dead neurons in a certain area, shakky movements in body

2 main neural circuits domain uses

ventral tegementam -> bottom part of brain to ventral straigam ->

*** communication pathaways

miso cortical limbic pathaway (motivation and cracing)
- reward, motivation

nigro striadal pathaway (movement)
[where] [where they connect]
- physical activity, race

*spatial scale*
synapses -> electric activity (less -> more activity)
vesicles
local release - synaptic release
volumetric release - vommits dopamin to hundreds of neurons

supplements decrease the diff between baseline and peak


*Duration of release*


neurons communicate via
- fast ionotropic conduction
- slow G-protein couple receptor

    passing exam sheets from front to back

dont release by themselves
- neurons that release dopamine corelease glutamate(excitatory)

- how enyoyable past activity

stimulates sympathetic arousal - more alert, ready outside of their skin

make you look outside yourself, pursue, crave

lethagic, lazy -> low dopamine
excited

Quality of live/ Desire
moving towards goal
how much dopamin wa there few moment ago
how much we remember enjoying a particular experience

it is a currency to pursue goals/ experience of life

*Spatial and Temporal Scale of Dopamine Transmission*
nature research


Anecdotes

thoraxine
LDOPA

*Baseline of Dopamine and Peaks of Dopamine*
genetic,

close cousine of - epinefrine, adrenaline (kidney, brain), dopamine make adrenaline

conversion
LDOPA -> dopamine -> noradrenaline -> adrenaline
                      (fear, mental trauma)

using a broad brush

acitivites that release dopamine

- chocolate (1.5)
- sex - pursuit, act (2.0)
- nicotine - smoked (2.5)
- cocaine -  (2.5)
- emphatamine -  (10)
- exercise - subjective like (2) or no reaction (0)
- gournalling about someting that they like increase
- subjective activities
- caffeine ()

increase the density of G-protein receptors

*why we have dopamine system?*

make more of ourself

foraging / seeking

doing something which you love repetedly will decrease the pleasure

*Dopamine Nation*

Pleasure / Pain Balance


Addiction

*intermittent release of dopamine*

*dont layer dopamin systems*

like - [music, podcast, ..., texting] + [workout, coding, ..]

removing multiple sources of dopamine releasing activities from activities that you enjoy.
caffeine is good for improving the dopamine circuitry

*sustained dopamine of dopamine*
cold exposure (vim hoff)
releases epinefrine, noradrenaline
sustained rise in dopamine (~3H)

*positive and negative aspect of behaviour*

dont reward yourself after doing hard work that you enjoy.

so, no posting on insta your pictures.

learning to access reward from effort and doing.

*rob malenka : oxytocin and social connections trigger dopamine release*
engage in pursue quality, healthy relationships.
