#+title: What Happen When We Enter Google

i want understand what really happens


* what i know now.

12 nov 7 AM

**  I power on my Computer
i power on my computer. the BIOS starts and it loads few segment of physical disk in the memory.
essentially loading the bootloader program, this bootloader then loads my actual operating system.

kernel must be loaded first which essentially will control low level operations dealing with
disk drivers (which controls the devices i.e. disk, networking devices, peripherals etc)


then some windowing system like GNOME, KDE or propretiary implementation will come into play
which will provide GUI to the operating system, allowing programs to run in with GUI.


** I open google chrome
Google chrome is preinstalled.
after this when application is run. operating system will provide resources to application
ranging from memory, network, cpu cycles.


** entering the url
after typing google.com in the address bar and hint ENTER.

the *DNS resolution* will take place and i will have IP address of the server.

then there will be *TCP* *handshake* between my device and google's IP. upon successful completion
i will connect to server and via HTTP the content will get downloaded and the browser will
render the content.

after that javascript will also be loaded in the browser and that will make sure the page is
interactive.

