* Smartphone

So common, we can find multiple of them in a single household.

A person can use it as 
- *communication device* with Phone, Messaging, Video Calls
- *utilities* like wakes up to the alarm of one, do some quick math in Calculator
- *work* like meetings, email, calender, online banking, e-commerce, 
- *special usecases* like contract tracing during COVID
- *consumes content*  like music, movies, tv series, games, comics, youtube
- *social media* apps like , instagram, facebook, tinder 
- *produce content* like blogging, vlogging, games streaming,

To sum up, it's a useful tool.

If you want to do something, there is a high chance that it can be done on a smartphone.

Up until the moment i am writing this, i thought smartphones are just bad for some people like
but if we look closely it's just a reflection of who you are, if it distracts you
maybe you are the problem. But if i think more on it, it feels like it's way more complicated.

Lets explore

** A piece of a puzzle
The thing is we are a social animal, The relations around us influence many of our decisions.
The social media companies grew and are growing just because people when they started using 
smartphones found it much easier to connect with each other, 
It might be that easiness that might be reason why they have lost the value, 
I have talked to my friends on phone multiple times, but the case when we actually see each other
is entirely different. There is a different level of satisfaction which we all experience.



