* Entertainment Growing Up
I was an average student when i was growing up, in the evening i use to play, Now i rarely see it.
Most people either just are on their phone or they are just hanging out here and there. The people
of my generation are all too busy in their lives that they don't have time to play phyiscal games,
some have families, some have physical work. Few which do have time they just don't feel like they
have people to play with and that it is not possible now. The kids that are at age when i started 
playing, they just are on their phones or simply not interested that much in the sports.

We started with Black and White Salora TV with those antennas, and we have 2-3 channels like DD National,
DD News and sometimes DD Metro, We use to tune the antenna to watch it, the Shows we saw was i guess
Weekly like 
- Shaktimaan, a superhero who has awakened all his chakra which premiered every Sunday.
- Rangoli, which gave us songs on Saturday.
and that was it.

Around 2002, we had a LG Colored CRT TV and CableTV. the channels increased in number and we had 
- SaharaONE, a programme Just Kids, with shows like, Mowgli, Book of Life, Cinderella, Zoro, Cristopher Columbus.
- ETV Binhar which had snake catching show, and Papyrus.
Cartoon Network with shows in 
- Japanese Anime - Beyblade, Pokemon, GrandSazers, JustiRizers
- American shows - PowerPuff Girls, Code Name Kids next Door, Dexter's Laboratory, Popeye, Kick Buttowski, Tom & Jerry, Courage the Cowardly Dog, Camp Lazlo, EON kid, Samsher Sikander Chaddi Buddy,  
- Italian - Barbie, Winx Club 
- Indian - Krishna, Little Krishna, Hanuman, Balram, Motu & Patlu, Oggy & the cockroaches

then it was UTV Action and that let us watch hindi dubbed Hollywood and chinese movies,

it felt excess at times but it was fun and it only happened on weekends or holidays.

For work stuff, We used to visit PC Cafe, charged hourly some amount let us use internet services. what we used to do 
was just do important stuff and you are done there

For Us social life was just the social life we had in Schools, neighbourhood friends and friends that you make while playing at a new place.
Those were all physical events that led to new social connections.

