* Understand OOP through a imaginary Day in my Life Developer :p.
Bob, and Sally, and you are on same Streaming enginering team.

Paige, a 24 yr old girl from Texas came on the first day.
She is wearing white T-Shirt and Blue Jean.

you observed that she only wears T-Shirt and Jean
of colors white, blue and black.

you start working together and she seems to do her job well
as assist you and other team members . 

This is just a very short, constrained description of a situation. We are only talking
about people in a office environment and are only discussing those aspects including

attire,
task completion,
collaboration

There are a lots of things that is happening to each of the team members like
they are all sleeping, doing their personal chores, friends outside the office,
hobbies, and much much more. we cannot write everything about a situation but
only through some lens which in this example is professional office setting.
Context is key to apply constraints so that we can detemine some results.

This proces of only apply constraints is called *Abstraction*.

