* Smartphone

So common, we can find multiple of them in a single household.

A person can use it as 
- *communication device* with Phone, Messaging, Video Calls
- *utilities* like wakes up to the alarm of one, do some quick math in Calculator
- *work* like meetings, email, calender, online banking, e-commerce, 
- *special usecases* like contract tracing during COVID
- *consumes content*  like music, movies, tv series, games, comics, youtube
- *social media* apps like , instagram, facebook, tinder 
- *produce content* like blogging, vlogging, games streaming,

To sum up, it's a useful tool.

Lets explore

** a communication Device

*Age of Feature Phones*
My first phone was a black and white nokia, which had calling functionality (apart from games like carrom
which i was interested in). This was not a personal phone but for entire family and my father
would use it most of the time. Later on we would get phones if there was a need like going for some prep classes.

Some of these would have ability to play music files like mp3, watch videos via mp4, that we would get from our
nearest PC shops that would have them ranging from music to movies to dramas. we would do this transfer via memory
cards ranging from 1Gb - 32Gb to be most commonly seem and we would tell the shopkeeper to fill it.
I remember when i was in Patna for my prep classes, the person would charge Rs.5/movie. The reason, mobile internet was 
expensive and sometimes not available and reliable. 


*smartphones*
they came in popular around 2010s and only few could afford 
Being social creatures, the relations influence many of our decisions.
The social media companies grew and are growing just because people when they started using 
smartphones found it much easier to connect with each other, 
It might be that easiness that might be reason why they have lost the value, 
I have talked to my friends on phone multiple times, but the case when we actually see each other
is entirely different. There is a different level of satisfaction which we all experience.

** Distractions


Up until the moment i am writing this, i thought smartphones are just bad for some people like
but if we look closely it's just a reflection of who you are, if it distracts you
maybe you are the problem. But if i think more on it, it feels like it's way more complicated.

